### ISSUE TITLE
How to make the next prediction?

### ISSUE THREAD

**Issue by bestmaa** [piercus/track-assignement#2]
How do I track my data with an ID?

my real data is :
frame 1 : [
    {
        "x": 257.71136474609375,
        "y": 148.27408854166666,
        "w": 88.23892211914062,
        "h": 477.56673177083337
    },
    {
        "x": 203.64385986328125,
        "y": 51.832736545138886,
        "w": 31.817626953125,
        "h": 180.37204318576389
    },
    {
        "x": 257.5543518066406,
        "y": 108.84111192491319,
        "w": 35.40704345703125,
        "h": 115.29107666015624
    }
]

frame 2: [
    {
        "x": 255.473388671875,
        "y": 154.87613932291666,
        "w": 89.0001220703125,
        "h": 470.82313368055554
    },
    {
        "x": 254.80429077148438,
        "y": 112.263671875,
        "w": 35.91455078125,
        "h": 125.06287977430554
    },
    {
        "x": 206.9302215576172,
        "y": 50.14846462673611,
        "w": 31.339019775390625,
        "h": 179.64976671006943
    }
]

**Comment by piercus** [comment]
Have you tried something ?

You can just consider your IDs as your indexes in frames 1, define the tracks at frame 1 then run a matching stage by using your frame2 as detections.

In order to use the iou function from `mean-average-precision` you will need to reformat your boxes using `formatBoxes``

I have rewritten the example from the doc below
NB: I haven't tested it yet, I let you correct this on your side.

```js
const map = require('mean-average-precision');
const {MatchingStage} = require('track-assignement');

const formatBoxes = function(b){
  return [b.x, b.y, b.w, b.h];
}

const matchingStage = new MatchingStage({
  distances: { iou: (track, detection) => (1-map.iou(, formatBoxes(detection))},
  order: ["iou"],
  lambdas: {"iou": 1},
  thresholds: {"iou": 1}
});

const detectionsFrame2 = [
    {
      "x": 255.473388671875,
      "y": 154.87613932291666,
      "w": 89.0001220703125,
      "h": 470.82313368055554
    },
    {
      "x": 254.80429077148438,
      "y": 112.263671875,
      "w": 35.91455078125,
      "h": 125.06287977430554
    },
    {
      "x": 206.9302215576172,
      "y": 50.14846462673611,
      "w": 31.339019775390625,
      "h": 179.64976671006943
    }
  ];

const tracks = [[
    {
      "x": 257.71136474609375,
      "y": 148.27408854166666,
      "w": 88.23892211914062,
      "h": 477.56673177083337
    },
    {
      "x": 203.64385986328125,
      "y": 51.832736545138886,
      "w": 31.817626953125,
      "h": 180.37204318576389
    },
    {
      "x": 257.5543518066406,
      "y": 108.84111192491319,
      "w": 35.40704345703125,
      "h": 115.29107666015624
    }
  ].map(formatBoxes)];

const newTracks = matchingStage.match({detections, tracks})
console.log(newTracks)
```
